### ISSUE TITLE
Bricksync decided to delete updated BL inventory instead of pushing the updates to BO

### ISSUE THREAD

**Issue by legoman666** [ZZJHONS/Bricksync#1]
Instead of pushing my updated inventory, it decided to delete every item I had just spent the past hour counting and adding.

`16:09:26 LOG: User command "sync"
16:09:26 INFO: BrickLink service flagged for deep sync.
16:09:26 INFO: BrickOwl service flagged for deep sync.

16:09:26 INFO: Fetching the BrickLink Order List...
16:09:26 INFO: Fetching the BrickLink Inventory...
16:09:28 INFO: Fetching the BrickLink Order List...
16:09:28 INFO: BrickLink inventory has 568 items in 65 lots.
16:09:28 LOG: Listing all changes to be pushed to BrickLink.
LOG: Adjust quantity by -33, ID 2867, Name "Train, Track 9V Curve", Used, Color 10, Quantity 78
LOG: Set Price from 0.600 to 0.700, ID 2867, Name "Train, Track 9V Curve", Used, Color 10, Quantity 78
LOG: Adjust quantity by -18, ID 2867, Name "Train, Track 9V Curve", Used, Color 85, Quantity 34
LOG: Set Price from 0.900 to 0.700, ID 2867, Name "Train, Track 9V Curve", Used, Color 85, Quantity 34
LOG: Delete orphan item, ID 10248stk01, Name "Sticker for Set 10248 - &#40;21016/6112603&#41;", New, Quantity 1
LOG: Delete orphan item, ID 2861, Name "Train, Track 9V Switch Point Left", Used, Color 10, Quantity 6
LOG: Delete orphan item, ID 2859, Name "Train, Track 9V Switch Point Right", Used, Color 10, Quantity 5
LOG: Delete orphan item, ID 32087, Name "Train, Track 9V Crossing", Used, Color 10, Quantity 1
LOG: Delete orphan item, ID 2861, Name "Train, Track 9V Switch Point Left", Used, Color 85, Quantity 1
LOG: Delete orphan item, ID 2859, Name "Train, Track 9V Switch Point Right", Used, Color 85, Quantity 1
LOG: Delete orphan item, ID 2865, Name "Train, Track 9V Straight", Used, Color 10, Quantity 188
LOG: Delete orphan item, ID 2865, Name "Train, Track 9V Straight", Used, Color 85, Quantity 61
16:09:28 INFO: Updating BrickLink inventory, 10 lots are pending for update.
LOG: Queued BrickLink Query: Update item "2867", color 10; Quantity adjust by -33; Set price to 0.700
LOG: Queued BrickLink Query: Update item "2867", color 85; Quantity adjust by -18; Set price to 0.700
LOG: Queued BrickLink Query: Delete item "2865", LotID 192201886
LOG: Queued BrickLink Query: Delete item "2865", LotID 192201902
LOG: Queued BrickLink Query: Delete item "2861", LotID 192198527
LOG: Queued BrickLink Query: Delete item "2859", LotID 192198535
LOG: Queued BrickLink Query: Delete item "2861", LotID 192200567
LOG: Queued BrickLink Query: Delete item "2859", LotID 192200576
LOG: Success updating BrickLink item "2867", color 10
LOG: Queued BrickLink Query: Delete item "32087", LotID 192198555
LOG: Success updating BrickLink item "2867", color 85
LOG: Queued BrickLink Query: Delete item "10248stk01", LotID 191781658
LOG: Success deleting BrickLink item "2865", color 10
LOG: Success deleting BrickLink item "2865", color 85
LOG: Success deleting BrickLink item "2861", color 10
LOG: Success deleting BrickLink item "2859", color 10
LOG: Success deleting BrickLink item "2861", color 85
LOG: Success deleting BrickLink item "2859", color 85
LOG: Success deleting BrickLink item "32087", color 10
LOG: Success deleting BrickLink item "10248stk01", color 0
16:09:29 INFO: BrickLink inventory update has completed.
16:09:29 INFO: Fetching the BrickOwl Order List...
16:09:29 INFO: Fetching the BrickOwl Inventory...
16:09:32 INFO: Fetching the BrickOwl Order List...
16:09:32 INFO: BrickOwl inventory has 237 items in 53 lots.
16:09:32 LOG: Listing all changes to be pushed to BrickOwl.
16:09:32 INFO: No update required for BrickOwl, we have a perfect inventory match.
16:09:36 INFO: Fetching the BrickOwl Order List...
16:09:36 INFO: We are up-to-date on BrickOwl orders.`

**Comment by ZZJHONS** [comment]
Sync check BL and BO against the inventory file of BS, you should have used blmaster on and blmaster off commands instead.
