### ISSUE TITLE
Updated colortable.c File

### ISSUE THREAD

**Issue by shaggyonjd** [ZZJHONS/Bricksync#10]
I've got another updated colortable.c file, that includes a few more missing colours;
Transparent Light Green
Transparent Light Bright Green
Transparent Purple Opal / Satin Trans-Purple

Not a huger number of parts in those colours but would be a helpful addition.

**Comment by ZZJHONS** [comment]
@shaggyonjd do you know how to do a pull request in Github? If not you can share the file here and i can update the code.
Thank you very much :)

**Comment by shaggyonjd** [comment]
[colortable.c.txt](https://github.com/ZZJHONS/Bricksync/files/6467856/colortable.c.txt)

**Comment by ZZJHONS** [comment]
File updated, thanks!

https://github.com/ZZJHONS/Bricksync/commit/dd96d129e95326107ae62466cdd4de390dad0ccf
