### ISSUE TITLE
New Colour - Vibrant/Neon Yellow

### ISSUE THREAD

**Issue by beaverbrick** [ZZJHONS/Bricksync#14]
New colour released;
Lego name is Vibrant Yellow.
BrickOwl name is Vibrant Yellow.
BrickLink name is Neon Yellow.

**Comment by beaverbrick** [comment]
I've got an updated colour file for this.
Will create a pull request.

**Comment by ZZJHONS** [comment]
I think there are also a few new colors since the last addition:

https://www.bricklink.com/catalogColors.asp?sortBy=N

Could you any of these too if it isn't much more hassle? 

Thanks you for your time and sharings.

**Comment by beaverbrick** [comment]
I'll take a look :)

**Comment by beaverbrick** [comment]
Couple more colours added :)
