### ISSUE TITLE
Bricksync backup issue

### ISSUE THREAD

**Issue by casper061198** [ZZJHONS/Bricksync#24]
Hi

I messed up my updated inventory with Bricksync, and I am having problems restroring
it

The log file says that backup no. 00182 was created after checking I have 580k
parts in my Bricklink inventory

16:39:17 INFO: BrickLink inventory has 579960 items in 7971 lots.
16:39:17 INFO: Saving backup of BrickLink inventory at "data\backups\2023-08-19\00182.bsx".

But when i open the 00182 file in Brickstock, it has the old inventory of 390k
parts

My new parts are put into drawers which I noted in the remark field, so now they
are impossible for me to find, as I can not simply upload them again

Please advice!

Casper

**Comment by ZZJHONS** [comment]
Do you have any newer backup and older one 181 and 183?

Can you share the .bsx files here?

**Comment by casper061198** [comment]
Den søn. 20. aug. 2023 kl. 00.43 skrev Sergio S. G. <
***@***.***>:

**Comment by casper061198** [comment]
Den søn. 20. aug. 2023 kl. 11.24 skrev Casper Olsson ***@***.***

**Comment by casper061198** [comment]
Hi sent the .bsx 181, 182, 183 via email as Github won't allow me to upload it here

Here's the log

Thanks!

[bricksync-2023-08-19.txt](https://github.com/ZZJHONS/Bricksync/files/12387679/bricksync-2023-08-19.txt)

**Comment by ZZJHONS** [comment]
I didn't get anything, try making a zip file with them together or upload to a hosting site if Github doesn't let you.

Also the command loadall is only for copy lot data (not quantity) from the ones matching in the file with your inventory in Bricklink

**Comment by casper061198** [comment]
[Bricklink.zip](https://github.com/ZZJHONS/Bricksync/files/12410752/Bricklink.zip)
Here is the zip, thanks!

**Comment by casper061198** [comment]
To sum up, the issue seems to be at backup #182, where the logs says that I had around 580.000 parts. I messed up in Bricksync, I know, but when I try to restore using my backup, the file doesn't contain the right amount of parts. When I open my backup files in Brickstock, they all have around 390.000 parts

Thanks,

Casper

**Comment by ZZJHONS** [comment]
Even in the file 181 you have around 390.000 parts, maybe you have duplicate lots in your store? Bricksync only works correctly if you only have 1 lot for each part in each condition. Duplicate lots are not backed up.

**Comment by casper061198** [comment]
It is not duplicates unfortunately, on Aug 16th I uploaded a lot of new sets which were parted out, these rose my inventory from 390k to 580k

I then remarked some of my new parts, and now they are lost in my drawers, as they are gone in the system. It is very strange that the backup files doesn't seem to be correct

I can even see my part out log on Bricklink, all looks ok..

Casper

**Comment by ZZJHONS** [comment]
After adding the lots in the Bricklink website did you enter the commands `blmaster on` and then `blmaster off`?

**Comment by BasKrie** [comment]
from the log:
18:16:44 LOG: User command "backup 00182bsx"
18:16:44 INFO: We saved a backup of the tracked inventory to "00182.bsx".

And that may be the reason that file 00182 contains the old inventory.
Still going through the log (83862 lines) to see how it went.
But conclusion is that your current backup file, in itself, is useless to restore your new inventory.

Possible course of action.
Load the backup from before 19-8 in to Brickstore (maybe that would be 00181)
Import, in Brickstore, the sets (and quantities) that you parted out
Part them out in Brickstore
Add those items to the opened backup 00181
Open all order files that were done after the 00181 backup
Delete the items in those orders from the 00181
That should give you a correct inventory.

For the remarks, all items sold on BL will be stated in the order files, so you can get them from there.
Others may be found in the log file that you posted here.
And yes, that means going through about 1500 lots, I don't see an automatic way of doing it.
Maybe you don't have to them all at once, but do them at the moment you get an order, would mean you will need more time gathering orders, but could open up shop earlier.
It will be a lot of work to do :(

Once you get your inventory correct in BrickStore, check if it is correct with your real inventory. Not all items have to be checked, but check the ones that were sold on 18 and 19 August.

Make a backup from your BL inventory with BrickStore
Then, delete your complete inventory from BL and BO
And upload (in batches) a new inventory with Brickstore
Then do a BLmaster on/of in Bricksync

Now everything should be in good order.

It may be that your closed BL store can't be edited, in that case, set a very high minimum order amount (larger than the inventory total) and open your store.

**Comment by BasKrie** [comment]
You maybe have another option.
Just noticed you are using OneDrive.
There may be an option to retrieve an earlier copy from the 00182 file (the one BS made with all items from BL),

Just right klik the file and choose version history (or something like that) and look to see if the original file is still there

**Comment by casper061198** [comment]
Hi, thanks for your replies!

No, I did not use the blmaster setting when parting out on Bricklink

Luckily, I only had one order after parting out, and I didn't remark all my new lots, only a few hundred, so they can be found

Unfortunately, the OneDrive doesn't show any earlier versions of the 182 file

Again, the help is highly appreciated,

Thanks,

Casper

**Comment by BasKrie** [comment]
There is chance that the file is in the onedrive recylcle bin.

**Comment by casper061198** [comment]
Unfortunately not..

**Comment by ZZJHONS** [comment]
Do you have all the items in the Bricklink website? then do blmaster on/off, you have to use it always you edit something in Bricklink.
