### ISSUE TITLE
Bricksync removing inventory 

### ISSUE THREAD

**Issue by ausward** [ZZJHONS/Bricksync#28]
When I add inventory on the bricklink site instead of updating brickowls inventory it is deleting the added bricks on bricklink

**Comment by Randallflagg0** [comment]
And you are using the blmaster on command, adding inventory to bricklink then running blmaster off?

**Comment by ausward** [comment]
Neither. I am adding the inventory to Bricklink.com. I am uploading XML from BrickStore

**Comment by Randallflagg0** [comment]
Before you upload you always run the command blmaster on (this is Bricklink master mode on), upload xml, then run blmaster off which will sync changes from the bricklink side to Brickowl, only this one direction.  This is the basic functionality of Bricksync.

I would suggest to read up on the how to use section as you can really make your inventory a mess without using this software properly, but this is the main issue that can cause inventory issues, never edit/add/change/anything without running "blmaster on" first.

**Comment by ausward** [comment]
Yeah guess I should have RTFD
