### ISSUE TITLE
Compiling on Linux

### ISSUE THREAD

**Issue by farinha** [ZZJHONS/Bricksync#3]
Hi,

I'm trying to compile a fresh version of BrickSync to get the newer colors working.
A brute-force "compile everything in folder" is complaining of a missing file:

```
bntest.c:39:10: fatal error: env.h: No such file or directory
 #include "env.h"
          ^~~~~~~
compilation terminated.
```
And sure enough, there is no `env.h` file anywhere.

Was this file left out of the sources by mistake? Is there any way to recover it?

**Comment by ZZJHONS** [comment]
Hello,

The original SC can be found here: http://www.bricksync.net/bricksync-src.tar.gz

And I don't see that file there neither.

The only changes made are the ones that can be seen in the commits.

To compile it be sure to leave out the Releases folder.

I have the latest code compiled and running good in Linux.

Did you read the Readme.md?

**Comment by farinha** [comment]
Can you tell me how you compiled the code?

Or help me figure out what I did wrong?

I cloned the repository on a Ubuntu machine.
Then navigated to the Bricksync folder and, as you suggest, removed the `README.md` file and the `Releases` folder.
Ran `gcc *.c -o bricksync`
This threw up a wall of warnings and 3 errors:

```
bntest.c:39:10: fatal error: env.h: No such file or directory
 #include "env.h"
          ^~~~~~~
compilation terminated.
eval.c: In function ‘main’:
eval.c:265:3: warning: ‘return’ with no value, in function returning non-void
   return;
   ^~~~~~
eval.c:163:5: note: declared here
 int main()
     ^~~~
oauth.c:39:10: fatal error: openssl/evp.h: No such file or directory
 #include <openssl/evp.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
rsaprime.c: In function ‘MillerRabin’:
rsaprime.c:123:11: warning: implicit declaration of function ‘rsaModularMultiplication’ [-Wimplicit-function-declaration]
       x = rsaModularMultiplication( x, base, n );
           ^~~~~~~~~~~~~~~~~~~~~~~~
tcp.c:92:11: fatal error: openssl/ssl.h: No such file or directory
  #include <openssl/ssl.h>
           ^~~~~~~~~~~~~~~
compilation terminated.
```
And this is where I'm stuck. If the file isn't there how can one compile the code?

**Comment by ZZJHONS** [comment]
Here are all the comments the original author made about compiling the software:

https://www.brickowl.com/forum#/discussion/comment/38325

**Comment by farinha** [comment]
The `compile` file contains the commands for compiling on Linux, which is a step in the right direction.

But running it still comes back with an error:

```
oauth.c:158:14: error: storage size of ‘mdctx’ isn’t known
EVP_MD_CTX mdctx;
^~~~~
```
Any ideas on how to fix this?

**Comment by ZZJHONS** [comment]
I think it you may have installed a newer version of OpenSSL:

https://stackoverflow.com/questions/55992010/openssl-error-storage-size-of-ctx-isn-t-known

**Comment by farinha** [comment]
Yes, that did it!

Added the call to EVP_MD_CTX_new() and EVP_MD_CTX_free() and changed the mdctx variable declaration and usage as necessary.
Also removed the calls to EVP_MD_CTX_cleanup() as that doesn't exist anymore.

It is now compiling with OpenSSL 1.1.1

I'll leave it running for a few days and if it's all good I'll open a pull request.

**Comment by farinha** [comment]
After a few days it seems it's all running fine so I've created a pull request to incorporate the changes: #5
