### ISSUE TITLE
Instructions to compile on Debian

### ISSUE THREAD

**Issue by ChristianGrieger** [ZZJHONS/Bricksync#31]
Are there instructions to compile on Linux (Debian)?

**Comment by ZZJHONS** [comment]
Download the source code and run ./compile withing the folder.

**Comment by ChristianGrieger** [comment]
I get this result but not the compiled file?

root@sd-xxx:~/apps/Bricksync# ./compile 
Detecting CPU features...

Arch : AMD64
Vendor : GenuineIntel
Identifier : Intel(R) Xeon(R) CPU E5-1650 0 @ 3.20GHz
Family : 6
Model  : 45
Cache Line Size  : 64 bytes
Cache Flush Size : 64 bytes
Processor Layout
  Socket Logical Cores  : 32
  Socket Physical Cores : 16
  Total Cores Count     : 12
Word Size    : 64 bits
GP Registers : 16
FP Registers : 16
User-Space Memory : 67392708608 bytes ( 64270.70Mb )
Capabilities : CMOV CLFLUSH TSC MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AES PCLMUL CMPXCHG16B MOVBE RDTSCP ConstantTSC HyperThreading MWAIT LongMode ThermalSensor ClockModulation
L1 Code Cache Memory
  Cache Size    : 32 kb
  Line Size     : 64 bytes
  Associativity : 8 way(s)
  Shared        : 2 core(s)
L1 Data Cache Memory
  Cache Size    : 32 kb
  Line Size     : 64 bytes
  Associativity : 8 way(s)
  Shared        : 2 core(s)
L2 Cache Memory
  Cache Size    : 256 kb
  Line Size     : 64 bytes
  Associativity : 8 way(s)
  Shared        : 2 core(s)
L3 Cache Memory
  Cache Size    : 12288 kb
  Line Size     : 64 bytes
  Associativity : 16 way(s)
  Shared        : 32 core(s)
Target Compiler : GCC 10.2
  GCC best options require 4.6 : Okay!
Recommended CC Options : -march=corei7-avx -mmmx -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -mavx -maes -mpclmul -mcx16 -mmovbe -m64 -mpreferred-stack-boundary=5
Compiler Version : 10.2.1 20210110

New cpuconfig.h file generated.
