### ISSUE TITLE
Issue with openssl when compiling

### ISSUE THREAD

**Issue by Yayaa10** [ZZJHONS/Bricksync#39]
Hello,can someone help me with compiling in linux ubuntu ?
when I try to compile,I have 2 errors:

```
tcp.c:92:11: fatal error: openssl/ssl.h: Aucun fichier ou dossier de ce type
   92 |  #include <openssl/ssl.h>
      |           ^~~~~~~~~~~~~~~
compilation terminated.
oauth.c:39:10: fatal error: openssl/evp.h: Aucun fichier ou dossier de ce type
   39 | #include <openssl/evp.h>
```

The compilation generate the cpuconf file only
My version of openssl is OpenSSL 3.0.2
Any issue with the version of openssl ?

I have reach to use the file compiled from the website bricksync.net but no way to compile it....

**Comment by HelloFromEarth** [comment]
Have you installed libssl-dev?  sudo apt-get install libssl-dev

**Comment by Yayaa10** [comment]
Thanks I have reach to compile on ubuntu!
There are others depencies ? On another machine I have issues with mmatomic and mmbitmap

`In file included from bricksync.c:37:`
`mmatomic.h:2316:3: warning: #warning mmatomic.h: No atomic support [-Wcpp]`
` 2316 |  #warning mmatomic.h: No atomic support`
`      |   ^~~~~~~`
`In file included from bricksync.c:38:`
`mmbitmap.h:31:3: warning: #warning Compiling mmbitmap without atomic support, it is going to be SLOW. [-Wcpp]`
`   31 |  #warning Compiling mmbitmap without atomic support, it is going to be SLOW.`
`      |   ^~~~~~~`

And finally I think a memory issue:
`In file included from mmbitmap.c:35:`
`mmbitmap.c: In function ‘mmBitMapInit’:`
`mmbitmap.c:64:51: error: ‘mmAtomicL’ undeclared (first use in this function)`
`   64 |     if( !( bitmap->map = malloc( mapsize * sizeof(mmAtomicL) ) ) )`
`      |                                                   ^~~~~~~~~`

the firsts lines are:
`Detecting CPU features...`

`Identifier : Unknown`
`Cache Line Size  : 32 bytes`
`Processor Layout`
`Word Size    : 64 bits`
`Capabilities :`
`Target Compiler : GCC 12.2`
`  GCC best options require 0.0 : Okay!`
`Compiler Version : 12.2.0`
