### ISSUE TITLE
Update Release?

### ISSUE THREAD

**Issue by BrickSouth** [ZZJHONS/Bricksync#4]
Is it possible to get a new release with the color additions and the recent Brickstore compatibility?

**Comment by ZZJHONS** [comment]
Hello @BrickSouth I would need help too to compile this in all the systems, as of now I only can for Linux.

Also, I will try the Pull Request #5 before so if we can compile a new release, it would be with all updated.

**Comment by ZZJHONS** [comment]
@BrickSouth could you check this test release: https://github.com/ZZJHONS/Bricksync/actions/runs/704164555

**Comment by BrickSouth** [comment]
Well, it seems to be getting stuck fetching the Bricklink inventory. It says No reply received for query, we will retry. But then it fails after that. I put in my API keys so I am good there.

**Comment by ZZJHONS** [comment]
> It looks like it works! I was having trouble at first, but I realized I needed to just replace the .exe and it worked.

Yes, to update it is only needed to replace the bricksync file.
Let it work a few days and let me know if everything went good so I can update the readme file for all.

**Comment by ZZJHONS** [comment]
@BrickSouth a new release with updated to OpenSSL can be downloaded here: https://github.com/ZZJHONS/Bricksync/actions/runs/712450306

**Comment by BrickSouth** [comment]
Awesome, thanks for doing this!
