### ISSUE TITLE
API  change on BL causes error: PARAMETER_MISSING_OR_INVALID

### ISSUE THREAD

**Issue by Caryntjen** [ZZJHONS/Bricksync#40]
BrickFreedom had similar error: https://www.bricklink.com/messageThread.asp?ID=353397&nID=1452018

Error received while uploading new parts:
==== DATA ====
{"meta":{"description":"String input must not be null","message":"PARAMETER_MISSING_OR_INVALID","code":400}}
==== END ====

**Comment by ZZJHONS** [comment]
Bricklink seems to now need the description too when making QTY updates

**Comment by Caryntjen** [comment]
Indeed:
The fix is to specify the "description" field.

{"quantity":4, "description":""}

**Comment by ZZJHONS** [comment]
Fixed on latest release: https://github.com/ZZJHONS/Bricksync/releases/tag/v1.7.4-Feb2nd2024
