### ISSUE TITLE
Compilation problems with EVP_MD_CTX_new /_free

### ISSUE THREAD

**Issue by DenHae** [ZZJHONS/Bricksync#42]
I'm trying to compile the latest Bricksync version but I'm getting the following error when executing the compile command:

oauth.c: In function 'oauthHmacSHA1':
oauth.c:162:11: warning: implicit declaration of function 'EVP_MD_CTX_new' [-Wimplicit-function-declaration]
   mdctx = EVP_MD_CTX_new();
           ^
oauth.c:162:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   mdctx = EVP_MD_CTX_new();
         ^
oauth.c:196:3: warning: implicit declaration of function 'EVP_MD_CTX_free' [-Wimplicit-function-declaration]
   EVP_MD_CTX_free( mdctx );
   ^
/tmp/ccut7pSx.o: In function `oauthQueryComputeSignature':
oauth.c:(.text+0x5fb): undefined reference to `EVP_MD_CTX_new'
oauth.c:(.text+0x738): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status

I'm using an older version of Ubuntu Server. Does anyone have a hint for me?

**Comment by ZZJHONS** [comment]
For an old version you would need to also use the old version of oauth.c before this change:

https://github.com/ZZJHONS/Bricksync/commit/a46f3058237438b1cc84ddf97c62e0ada2772932

**Comment by DenHae** [comment]
Thanks, that worked perfectly!
