### ISSUE TITLE
Compile error in oauth.c

### ISSUE THREAD

**Issue by DenHae** [ZZJHONS/Bricksync#9]
First of all: Thanks so much for taking care of this project and providing updates.

I decided to compile my own binaries of version 1.7.2-3 as my Ubuntu server does not support a newer version of openssl than 1.0.4.

For compilation I just use the 'compile' file that is provided in the project but I get the following error:

oauth.c: In function 'oauthHmacSHA1':
oauth.c:162:11: warning: implicit declaration of function 'EVP_MD_CTX_new' [-Wimplicit-function-declaration]
   mdctx = EVP_MD_CTX_new();
           ^
oauth.c:162:9: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   mdctx = EVP_MD_CTX_new();
         ^
oauth.c:196:3: warning: implicit declaration of function 'EVP_MD_CTX_free' [-Wimplicit-function-declaration]
   EVP_MD_CTX_free( mdctx );
   ^
/tmp/cckQIbYa.o: In function `oauthQueryComputeSignature':
oauth.c:(.text+0x5fb): undefined reference to `EVP_MD_CTX_new'
oauth.c:(.text+0x738): undefined reference to `EVP_MD_CTX_free'
collect2: error: ld returned 1 exit status

Do you have any idea what the problem is? (my system setup, the compile file or coding?)

Best regards,
 Dennis

**Comment by ZZJHONS** [comment]
To compile the latest code it is needed OpenSSL 1.1.1 in the system too.

An option that you can try is downgrading the file oauth.c that was changed in this commit:
https://github.com/ZZJHONS/Bricksync/commit/a46f3058237438b1cc84ddf97c62e0ada2772932
